name: 🐛 Rapport de Bug
description: Signaler un bug ou un problème
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug. Plus d'informations = meilleure résolution !
  
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement et en détail le bug rencontré
      placeholder: "Ex: Lorsque je clique sur le bouton de réservation, l'application crash..."
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Décrivez les étapes pour reproduire le problème
      placeholder: |
        1. Aller sur la page X
        2. Cliquer sur Y
        3. Voir l'erreur
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
      placeholder: "Le bouton devrait ouvrir le formulaire de réservation..."
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: "L'application crash avec l'erreur..."
    validations:
      required: true
  
  - type: dropdown
    id: platform
    attributes:
      label: Plateforme
      description: Sur quelle plateforme le bug apparaît-il ?
      options:
        - Android
        - iOS
        - Les deux
        - Web
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Version de l'application
      description: Version actuelle (visible dans les paramètres)
      placeholder: "1.0.0+1"
    validations:
      required: true
  
  - type: input
    id: device
    attributes:
      label: Appareil
      description: Modèle de l'appareil (ex: iPhone 14, Samsung Galaxy S23)
      placeholder: "iPhone 14 Pro"
  
  - type: input
    id: os
    attributes:
      label: Version OS
      description: Version du système d'exploitation
      placeholder: "iOS 17.0 / Android 13"
  
  - type: textarea
    id: logs
    attributes:
      label: Logs / Erreurs
      description: Coller ici les logs ou messages d'erreur pertinents
      render: shell
      placeholder: "Flutter logs, stack traces, etc."
  
  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran pour illustrer le problème
      placeholder: "Glisser-déposer les images ici"
  
  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Tout autre détail pertinent
      placeholder: "Contexte additionnel, workarounds, etc."
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: J'ai vérifié que ce bug n'existe pas déjà dans les issues ouvertes
          required: true
        - label: J'ai testé sur la dernière version
          required: true
        - label: J'ai vérifié les logs pour plus d'informations
          required: false


